### ISSUE TITLE
pyLDAvis index 1098 is out of bounds for axis 1 with size 707

### ISSUE THREAD

**Issue by HaritzPuerto** [bmabey/pyLDAvis#72] opened 2016-09-10 15:32 UTC
I have the following exception:

```
IndexErrorTraceback (most recent call last)
<ipython-input-17-209fc1d6a743> in <module>()
----> 1 data1 =  pyLDAvis.gensim.prepare(lda_model_1, corpus1, dictionary)
      2 pyLDAvis.display(data1)

/usr/local/lib/python2.7/dist-packages/pyLDAvis/gensim.pyc in prepare(topic_model, corpus,   dictionary, doc_topic_dist, **kwargs)
 95     See `pyLDAvis.prepare` for **kwargs.
 96     """
---> 97     opts = fp.merge(_extract_data(topic_model, corpus, dictionary, doc_topic_dist), kwargs)
 98     return vis_prepare(**opts)

/usr/local/lib/python2.7/dist-packages/pyLDAvis/gensim.pyc in _extract_data(topic_model, corpus, dictionary, doc_topic_dists)
 26    beta = 0.01
 27    fnames_argsort = np.asarray(list(dictionary.token2id.values()), dtype=np.int_)
---> 28    term_freqs = corpus_csc.sum(axis=1).A.ravel()[fnames_argsort]
 29    term_freqs[term_freqs == 0] = beta
 30    doc_lengths = corpus_csc.sum(axis=0).A.ravel()

IndexError: index 1098 is out of bounds for axis 1 with size 707
```

I have asked to gensim google group and they have told me that my code seemed ok so I should ask here too.

 I want to build two LDA models with gensim which share a dictionary. So I have two corpus and one dictionary for both. You can see my code here (and you can reproduce the error):
https://gist.github.com/HaritzPuerto/993c8d07ede22e1649265c7f55220cf9

That exception only occurs when I apply ldavis to the first model. ldavis works well with the second model.
Please, find attached the data I've used.
[Data.zip](https://github.com/bmabey/pyLDAvis/files/465473/Data.zip)

Data about my pc:
Vagrant virtual machine with ubuntu 14.04, python 2.7 and pyldavis  1.5.1  

Do I have a problem with my code or is it a bug? A guy in the gensim google group told me that shared dictionary may have a conflict with pyldavis.

Thank you

**Comment by wyntonmoore** [comment] 2016-10-03 21:53
I had a similar error. I'm not an expert but can share what worked for me. The problem is that the corpus does not include all token ids present in the dictionary. If it so happens that the highest-index token in the dictionary is absent from the corpus, the resulting csc matrix will have too few rows, causing the index error. When the csc matrix is created in pyLDAvis.gensim._extract_data, you have to force the number of tokens to equal the length of the dictionary:

corpus_csc = gensim.matutils.corpus2csc(corpus, num_terms=len(fnames_argsort))

(Also shift the definition of fnames_argsort to the beginning of _extract_data)

**Comment by hurcy** [comment] 2016-12-01 03:38
I also have same error. Maybe this issue haven't updated recent release.
My env is ubuntu 16.04, python 2.7, pyldavis 2.0.0

I updated like @wyntonmoore said, and it works well. Thanks.

**Comment by theotheo** [comment] 2016-12-30 23:25
Sorry, but why wasn't it fixed?

**Comment by dariuspac** [comment] 2017-02-13 10:04
Hi guys,

one workaround did the trick for me. Its not the most intelligent solution and proper fix would be much better, but if the corpus is big enough this workaround shouldn't impact the results. And it doesn't require accessing LDAvis code. 

Based on what wyntonmoore suggested we could just find out last word in the dictionary and add it to the corpus. 
Simple code for illustration:

`lda=gensim.models.ldamodel.LdaModel.load("lda.model")`
```
doc_complete = ["A bear walked in the dark forest.",
             "Tall trees have many more leaves than short bushes.",
             "A starship may someday travel across vast reaches of space to other stars.",
             "Difference is the concept of how two or more entities are not the same."]
```
`doc_complete.append(lda.id2word[len(lda.id2word)-1]) #last corpus word is "jawbone"`

```
print(doc_complete)
['A bear walked in the dark forest.',
 'Tall trees have many more leaves than short bushes.',
 'A starship may someday travel across vast reaches of space to other stars.',
 'Difference is the concept of how two or more entities are not the same.',
 'jawbone']
```


```
doc_clean = [str(doc).split() for doc in doc_complete]
doc_term_matrix = [lda.id2word.doc2bow(doc) for doc in doc_clean]
vis_data =gensimvis.prepare(lda, doc_term_matrix, lda.id2word)
```

**Comment by alexsalles** [comment] 2017-02-13 13:11
Hi guys,

I believe that this issue has just been fixed in here #82. It implements the solution as proposed by @wyntonmoore .

**Comment by bmabey** [comment] 2017-02-13 16:14
Try the latest version, `v2.1.1`, to see if this is fixed for you.

**Closed by bmabey** 2017-02-13 16:14 UTC

**Comment by HaritzPuerto** [comment] 2017-02-13 18:13
Hi guys,
I've been disconnected for a while.
Latest version works great. It is fixed. Thank you! :)
